[package]
name = "mongo_connect"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "3.2.4"
tokio = "1.46.1"
dotenv = "0.15.0"
futures-util = "0.3.31"
chrono = "0.4.42"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
